### ISSUE TITLE
After updating library I'm facing lot's of errors

### ISSUE THREAD

**Issue by Bhagirath987** [highcharts/highcharts-android#223]
Old dependency implementation "com.highsoft.highcharts:highcharts:7.1.3"
New dependency  com.github.highcharts:highcharts-android:v9.3.2

Please check below errors
1 - View not found  
<com.highsoft.highcharts.core.HIChartView
                    android:id="@+id/hc"
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    app:layout_constraintBottom_toBottomOf="parent"
                    app:layout_constraintLeft_toLeftOf="parent"
                    app:layout_constraintRight_toRightOf="parent"
                    app:layout_constraintTop_toTopOf="parent" />

2 - below imports are not found.
com.highsoft.highcharts.common.hichartsclasses.HIColumn;
com.highsoft.highcharts.common.hichartsclasses.HIOptions;
com.highsoft.highcharts.common.hichartsclasses.HISeries;
com.highsoft.highcharts.core.HIChartView;

There are so many errors I'm facing.

**Comment by soommy12** [comment]
Hi @Bhagirath987 ! The right dependency to get the library is: `'com.github.highcharts:highcharts-android:9.3.2'` (no "v" before the version number). There was a mistake in docs, we've already corrected this.

**Comment by Bhagirath987** [comment]
Yes I have updated dependency as you mention but now I'm still getting many errors like 

1 HIDataLabelsOptionsObject can not found
2 hicssObject.setColor("gray");  now we can't set color like that 
there are so many issue with the code now

I hop you understand our situation. we have developed large size project and used highchart lib for charts now we have to change almost in every 2nd file that's not gud for us.

One more request can you please make below dependency available on github so we don't have to update dependency and project will work fine(Otherwise can you provide arr file of version 7.1.3 so we implement on or project and it will work as it is)
implementation "com.highsoft.highcharts:highcharts:7.1.3

**Comment by soommy12** [comment]
@Bhagirath987 unfortunatelly we do not support backwards compatibility and I strongly recommend you to switch to the newer version of the library. 7.x and 9.x are like two different generations, some options may be differently initialized now but many bugs and general improvements were done since 7.x. If you have any options that you have problems with you can copy them and I will try to help as much as I can to make them working as expected. For example, now, you should use `HIDataLabels` instead of `HIDataLabelsOptionsObject`. `HICSSObject` is still there but maybe the outer class style object is different (not sure which are you using).

However, if you really want to use older versions aar's, you can find them in the repository's [releases](https://github.com/highcharts/highcharts-android/releases) section. Although, I my advice is to use always the newest one and update it along with following releses.

**Comment by Bhagirath987** [comment]
Yes, I have resolve almost every errors as you said
Thank you so much man :) for quick response and your support
